steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/beatlink/github.com/cedricpierre/beatlink@sha256:${_IMAGE}
      - --cache=true
      - --cache-ttl=XXh
