steps:
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', '${_LOCATION}/github.com/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]
images:
  - '${_LOCATION}/github.com/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
